services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    ports:
      - "5432:5432"
    networks:
      - elt-pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dbt_data:

networks:
  elt-pipeline:
    driver: bridge